# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 03:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default=b'v1.0', max_length=10, verbose_name=b'report version')),
                ('hardware', models.CharField(default=b'', max_length=20, verbose_name=b'pi hardware')),
                ('revision', models.CharField(default=b'', max_length=20, verbose_name=b'pi revision')),
                ('serial', models.CharField(default=b'', max_length=20, verbose_name=b'pi serial')),
                ('public_ip', models.CharField(default=b'', max_length=20, verbose_name=b'public ip')),
                ('last_update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'last update time')),
                ('services', models.CharField(default=b'', max_length=100, verbose_name=b'service list')),
                ('local_ip_list', models.CharField(default=b'', max_length=100, verbose_name=b'local ip list')),
                ('public_key', models.CharField(default=b'', max_length=500, verbose_name=b'public key')),
            ],
        ),
    ]
